---
# tasks file for roles/ipaclient
#- name: Set server and generate certs
#    block:
    - name: Set hostname
      hostname:
         name: ipaclient.comp.local

    - name: Config hosts
      lineinfile:
         dest: /etc/hosts
         line: '{{ item }}'
      with_items:
            - '192.168.111.40 ipa.comp.local ipa'
            - '127.0.0.1 localhost'

    - name: configure name servers
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 192.168.111.40'

    - name: Install epel-release
      yum:
        name:
        - epel-release

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install ipa-client
      yum:
        name:
        - freeipa-client
        state: latest

    - name: ipa-client-install
      shell: ipa-client-install --mkhomedir --domain=comp.local --server=ipa.comp.local --realm=COMP.LOCAL --principal=admin --password=Qwerty123 --hostname=ipaclient.comp.local --no-ntp  --unattended      
